name: dotnet-core-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: helm setup
      run: curl -O https://get.helm.sh/helm-v3.3.4-linux-amd64.tar.gz && tar -zxvf helm-v3.3.4-linux-amd64.tar.gz
    - name: helm plugin setup
      run: /home/docker/actions-runner/_work/github-actions-service-b/github-actions-service-b/linux-amd64/helm plugin install https://github.com/chartmuseum/helm-push.git
    - name: helm repo add
      run: /home/docker/actions-runner/_work/github-actions-service-b/github-actions-service-b/linux-amd64/helm repo add chart-museum http://chartmuseum:8080
    - name: helm push
      run: /home/docker/actions-runner/_work/github-actions-service-b/github-actions-service-b/linux-amd64/helm push kubernetes/helm/service-b/ chart-museum
